apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbom-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbom-controller
  template:
    metadata:
      labels:
        app: sbom-controller
    spec:
      containers:
        - name: sbom-controller
          image: your-docker-image
          imagePullPolicy: Always
          command: ["./controller"]
